#pragma once
#include "core.h"

enum
{
    SUCCESS = 0,
    ERROR_TOKENIZER_INCOMPLETE_TOKEN,
    ERROR_PARSER_INHERITED,
    ERROR_PARSER_PREFIX_WITHOUT_LEFT,
    ERROR_PARSER_SUFFIX_WITHOUT_RIGHT,
    ERROR_PARSER_INFIX_WITHOUT_LEFT,
    ERROR_PARSER_INFIX_WITHOUT_RIGHT,
    ERROR_PARSER_INFIX_LONELY,
    ERROR_PARSER_IF_WITHOUT_CONDITION,
    ERROR_PARSER_IF_WITHOUT_BODY,
    ERROR_PARSER_ELSEIF_WITHOUT_CONDITION,
    ERROR_PARSER_ELSEIF_WITHOUT_BODY,
    ERROR_PARSER_OPERATOR_INVALID_CONTEXT,
};
typedef uint16_t RynError;

